// Autogenerated by gulp scripts. Do not edit
window.AppConfig = {
    "config": {
        "app_title": "Phoenix Code",
        "app_name_about": "Phoenix Code",
        "about_icon": "styles/images/phoenix-icon.svg",
        "how_to_use_url": "https://github.com/adobe/brackets/wiki/How-to-Use-Brackets",
        "docs_url": "https://docs.phcode.dev/",
        "support_url": "https://github.com/phcode-dev/phoenix/discussions",
        "suggest_feature_url": "https://github.com/phcode-dev/phoenix/discussions/categories/ideas",
        "get_involved_url": "https://github.com/phcode-dev/phoenix/discussions/77",
        "release_notes_url": "https://github.com/adobe/brackets/wiki/Release-Notes",
        "homepage_url": "https://phcode.io",
        "update_download_page": "https://phcode.io/",
        "twitter_url": "https://twitter.com/phcodedev",
        "youtube_url": "https://www.youtube.com/channel/UCNK2a8DKqPQQe3GlfTk-RHg",
        "troubleshoot_url": "https://github.com/adobe/brackets/wiki/Troubleshooting#wiki-livedev",
        "twitter_name": "@phcodedev",
        "contributors_url": "https://api.github.com/repos/phcode-dev/phoenix/contributors?per_page={0}&page={1}",
        "extension_listing_url": "",
        "extension_registry": "https://extensions.phcode.dev/registry.json",
        "extension_registry_version": "https://extensions.phcode.dev/registry_version.json",
        "extension_registry_popularity": "https://extensions.phcode.dev/popularity.json",
        "extension_url": "https://extensions.phcode.dev/extensions/",
        "extension_store_url": "https://store.core.ai/src/",
        "app_notification_url": "https://updates.phcode.io/appNotifications/prod/",
        "app_update_url": "https://updates.phcode.io/tauri/update-latest-stable-prod.json",
        "linting.enabled_by_default": true,
        "build_timestamp": "2024-11-27T05:00:50.423Z",
        "googleAnalyticsID": "G-FBK9RP5YK2",
        "googleAnalyticsIDDesktop": "G-M7MX9BYZZ3",
        "mixPanelID": "8cb6814f733e37c05cc59b4adad26407",
        "coreAnalyticsID": "phoenix",
        "coreAnalyticsAppName": "phoenix-prod",
        "coreAnalyticsAppNameDesktop": "desktop-prod",
        "environment": "production",
        "buildtype": "production",
        "bugsnagEnv": "production"
    },
    "name": "Phoenix Code",
    "version": "3.10.1-20683",
    "apiVersion": "3.10.1",
    "homepage": "https://core.ai",
    "issues": {
        "url": "https://github.com/phcode-dev/phoenix/issues"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/phcode-dev/phoenix.git",
        "branch": "",
        "SHA": ""
    },
    "licenses": [
        {
            "type": "AGPL-3.0-or-later",
            "url": "https://github.com/phcode-dev/phoenix/blob/master/LICENSE"
        }
    ]
};
