// Autogenerated by gulp scripts. Do not edit
window.AppConfig = {
    "config": {
        "app_title": "Phoenix",
        "app_name_about": "Phoenix",
        "about_icon": "styles/images/phoenix-icon.svg",
        "how_to_use_url": "https://github.com/adobe/brackets/wiki/How-to-Use-Brackets",
        "support_url": "https://github.com/phcode-dev/phoenix/discussions",
        "suggest_feature_url": "https://github.com/phcode-dev/phoenix/discussions/categories/ideas",
        "get_involved_url": "https://github.com/phcode-dev/phoenix/discussions/77",
        "glob_help_url": "https://github.com/adobe/brackets/wiki/Using-File-Filters",
        "release_notes_url": "https://github.com/adobe/brackets/wiki/Release-Notes",
        "homepage_url": "https://core.ai",
        "twitter_url": "https://twitter.com/phcodedev",
        "troubleshoot_url": "https://github.com/adobe/brackets/wiki/Troubleshooting#wiki-livedev",
        "twitter_name": "@phcodedev",
        "contributors_url": "https://api.github.com/repos/phcode-dev/phoenix/contributors?per_page={0}&page={1}",
        "extension_listing_url": "",
        "extension_registry": "https://brackets-archive.github.io/brackets-extensions/registry.json",
        "extension_registry_version": "https://brackets-archive.github.io/brackets-extensions/registry_version.json",
        "extension_url": "https://brackets-archive.github.io/brackets-extensions/extensions/",
        "extension_store_url": "https://store.core.ai/src/",
        "linting.enabled_by_default": true,
        "build_timestamp": "2023-01-17T11:23:33.860Z",
        "googleAnalyticsID": "G-FBK9RP5YK2",
        "mixPanelID": "8cb6814f733e37c05cc59b4adad26407",
        "coreAnalyticsID": "phoenix",
        "coreAnalyticsAppName": "phoenix-prod",
        "environment": "production",
        "buildtype": "production",
        "bugsnagEnv": "production"
    },
    "name": "Phoenix",
    "version": "3.1.5-19124",
    "apiVersion": "3.1.5",
    "homepage": "https://core.ai",
    "issues": {
        "url": "https://github.com/phcode-dev/phoenix/issues"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/phcode-dev/phoenix.git",
        "branch": "",
        "SHA": ""
    },
    "licenses": [
        {
            "type": "AGPL-3.0-or-later",
            "url": "https://github.com/phcode-dev/phoenix/blob/master/LICENSE"
        }
    ]
};
